services:
  db:
    image: mysql:8.0
    container_name: epicuria-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: epicuria
    ports:
      - "3306:3306"
    volumes:
      - epicuria_mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: epicuria-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  epicuria_mysql_data:
